language: node_js
node_js:
- '7'
dist: trusty
sudo: false
script:
- npm run build
- travis_wait 60 npm test
deploy:
  provider: npm
  email: niklasvh@gmail.com
  skip_cleanup: true
  api_key:
    secure: VNCakTt4ZrEybINXzyuD04iuyLuTp7lCjyULjaRLw+cLJXAvNelhdKi+jiae7902T8n52QJ+8dKsPi3RdS7TaNknJBRQxRAoX17LkqwjO09MvpsCVXMnrUchc3wcZw4wAeS4OCaD1zCLmoQbS26AYHalAZ1jtDoZ3XjQlglj9Jgp4E3NQn4FzESyHeS7c+H/lvhORlOxOkJn/0rSOABLS8hCY/6cJp0YYUXRX0elPXCktIwus8uoC2+27G1KKljZVsMhtKSH/8fA9huhDt+odyT637Xjz5eTcZPHaNTjZDlOhTlKPX92ZYp3T3GVitp80lIxj3W7etKmZcLekYmKLQLoFJaj1/CJC55eSvePh1jxkxBxvBmxsWG3hlpuIW3V3OjPWAqqxFRn3QlNEff5OhMiDmQNdWJVNTGvGvnjcWC3q80Sdt2NExuRmaIdONNl69MLSADw9Wo2M9ySA07k2ZCyHVZ2VIQ9CTA6mQ/g1fY2x3RbLgg4qD/RtYgcfu1YOPQ4Odx0XzEJb7YIG11CH54Q8HHETHl+w+nCDr0Kd6WCNdzJ4LJNFuTr8AWDmScm87w3qhsXvBYT8LjASeWBgR+L88gUWjCqx9FSRDc55UhgTuE7RO+7PSGXiDef3LzLKV5cGxvD3Z8zoJemotNscvhggcIBXoDQsh0EJNfjees=
  on:
    tags: true
    branch: master
    repo: niklasvh/css-line-break
